name: actions
on: [push]
jobs:
  FirstAction:
    runs-on: ubuntu-latest
    steps:
      - run: npm ci
      - run: npm run lint
  SecondAction:
    runs-on: ubuntu-latest
    steps:
      - run: echo ls
